### ISSUE TITLE
Invalid setting for webhdfs output plugin: "false"

### ISSUE THREAD

**Issue by loshkovskyi** [dstore-dbap/logstash-webhdfs#2]
Hello,

When using `compress => false` in my `Logstash 1.5` configuration file, I have encountered the following error:
```
Invalid setting for webhdfs output plugin:

  output {
    webhdfs {
      # This setting must be a [false, "snappy", "gzip"]
      # Expected one of [false, "snappy", "gzip"], got ["false"]
      compress => "false"
      ...
    }
  } {:level=>:error}
```
I am not expert in Ruby, but it looks like this option was not implemented. The `gzip` compression, for example, works fine.

**Comment by dstore-dbap** [comment]
HI there,

thanks for the heads up. Will have a look at it.

**Comment by dstore-dbap** [comment]
Should be fixed in 6bf57ea.

**Comment by loshkovskyi** [comment]
Thank you a lot.

**Comment by dstore-dbap** [comment]
You're very welcome ;)
